name: 'Install Dependencies'
description: 'Installs toolchain dependencies'
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          clang-tidy \
          libncurses-dev \
          build-essential \
          pkg-config \
          libx11-dev \
          libdrm-dev \
          libepoxy-dev \
          bindgen
      shell: bash
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Meson and Ninja
      run: python -m pip install --upgrade pip meson ninja pyyaml
      shell: bash
